// export default {
//   'Areas verdes':,
//   'Área de juegos para niños',
//   'Ascensor directo',
//   'Boulevard peatonal',
//   'Cancha de Fulbito',
//   'Cancha de Squash',
//   'Club House',
//   'Cuarto de servicio',
//   'Gimnasio',
//   'Jardín de niños',
//   'Karaoke',
//   'Lobby',
//   'Minimarket',
//   'Parque privado',
//   'Paseo de Aguas',
//   'Piscina',
//   'Sala Bar',
//   'Salón Gourmet',
//   'Sala de internet',
//   'Sala de Niños',
//   'Sala de cine',
//   'Sala de usos Múltuples',
//   'Sauna',
//   'Techo Panorámico',
//   'Techos Ecológicos',
//   'Terraza',
//   'Video vigilancia',
//   'Zona de Lavandería',
//   'Zona de Parrillas',
//   'Otros',
// };
